In [1]:
import os
import pandas as pd
import numpy  as np
import matplotlib.pyplot as plt
pd.options.display.max_rows = 10
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from pandas import DataFrame
from matplotlib import colors as mcolors

## Breast Cancer Prediction

In [2]:
Breast_Cancer = pd.read_csv("Breast_Cancer.csv",delimiter=';',decimal=".")
Breast_Cancer.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean           ...             radius_worst  texture_worst  \
0         0.2419           ...                    25.38          17.33   
1         0.1812           ...                    24.99          23.41   
2         0.2069           ...                    23.57          25.53   
3         0.2597           ...                    14.91          26.50   
4         0.1809           ...                    22.54          16.67   

   perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
0           184.60      2019.0            0.1622             0.6656   
1           158.80      1956.0            0.1238             0.1866   
2           152.50      1709.0            0.1444             0.4245   
3            98.87       567.7            0.2098             0.8663   
4           152.20      1575.0            0.1374             0.2050   

   concavity_worst  concave points_worst  symmetry_worst  \
0           0.7119                0.2654          0.4601   
1           0.2416                0.1860          0.2750   
2           0.4504                0.2430          0.3613   
3           0.6869                0.2575          0.6638   
4           0.4000                0.1625          0.2364   

   fractal_dimension_worst  
0                  0.11890  
1                  0.08902  
2                  0.08758  
3                  0.17300  
4                  0.07678  

[5 rows x 31 columns]

**Selecting the Predictor variable and Dependent variable**

In [3]:
X = Breast_Cancer.iloc[:,1:31] 

In [4]:
Y = Breast_Cancer.iloc[:,0:1] 
print(Y.head())

  diagnosis
0         M
1         M
2         M
3         M
4         M


In [5]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size=0.75, random_state=0)

D:\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [6]:
def general_indices(MC, names = None):
    global_precision = np.sum(MC.diagonal()) / np.sum(MC)
    global_error = 1 - global_precision
    precision_category  = pd.DataFrame(MC.diagonal()/np.sum(MC,axis = 1)).T
    positive_precision = (MC[1][1]/(MC[1][0] + MC[1][1])) * 100  #VP/(FN+VP)
    negative_precision= (MC[0][0]/(MC[0][0] + MC[0][1])) * 100 #VN/(VN+FP)
    falses_positives =   MC[0][1]/(MC[0][0] + MC[0][1])         #FP/(VN+FP)
    falses_negatives =   MC[1][0]/(MC[1][0] + MC[1][1])         #FN/(FN+VP)
    positive_assertiveness = MC[1][1]/(MC[0][1] + MC[1][1])       #VP/(FP+VP)
    negative_assertiveness = MC[0][0]/(MC[0][0] + MC[1][0])       #VN/(VN+FN)
    if names!=None:
        precision_category.columns = names
    return {"Confusion Matriz":MC, 
            "Global Precisión":global_precision, 
            "Global Error":global_error, 
            "precision category":precision_category,
            "Positive Precision":positive_precision,
            "Negative Precision":negative_precision,
            "Falses Positives":falses_positives,
            "Falsese Negatives":falses_negatives,
            "Positive Assertiveness":positive_assertiveness,
            "Negative Assertiveness":negative_assertiveness
           }

Using the Bayes, Linear Discriminant, and Quadratic Discriminant methods, generate predictive models for the learning table.

In [7]:
#Bayes
# Default Parameters
bayes = GaussianNB()
print(bayes)
#Training the model
bayes.fit(X_train, Y_train)
prediccion = bayes.predict(X_test)

MC = confusion_matrix(Y_test, prediccion)
indices = general_indices(MC,list(np.unique(Y)))
num_indices_list_bayes=[]
nom_indices_list_bayes=[]
for k in indices:
    print("\n%s:\n%s"%(k,str(indices[k])))
    num_indices_list_bayes.append(str(indices[k]))
    nom_indices_list_bayes.append(k)

print("The predictions using naive bayes are: {}".format(bayes.predict(X_test)))


GaussianNB(priors=None, var_smoothing=1e-09)

Confusion Matriz:
[[86  4]
 [ 5 48]]

Global Precisión:
0.9370629370629371

Global Error:
0.06293706293706292

precision category:
          B        M
0  0.955556  0.90566

Positive Precision:
90.56603773584906

Negative Precision:
95.55555555555556

Falses Positives:
0.044444444444444446

Falsese Negatives:
0.09433962264150944

Positive Assertiveness:
0.9230769230769231

Negative Assertiveness:
0.945054945054945
The predictions using naive bayes are: ['M' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'B' 'B' 'M' 'M' 'M' 'B' 'M'
 'M' 'M' 'M' 'M' 'B' 'B' 'M' 'B' 'B' 'M' 'B' 'M' 'B' 'M' 'B' 'M' 'B' 'M'
 'B' 'M' 'B' 'M' 'B' 'B' 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'M' 'M' 'M' 'B'
 'B' 'B' 'B' 'B' 'B' 'M' 'M' 'M' 'B' 'B' 'M' 'B' 'M' 'M' 'M' 'B' 'B' 'M'
 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'M' 'M' 'M' 'B' 'M' 'B' 'B' 'B' 'M' 'M'
 'B' 'B' 'B' 'M' 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'B' 'M' 'B'
 'B' 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M

D:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [8]:
#linear discriminant methods
# Default parameters
lda = LinearDiscriminantAnalysis(solver = 'lsqr', shrinkage = 'auto')
print(lda)
lda.fit(X_train, Y_train)
prediccion = lda.predict(X_test)

MC = confusion_matrix(Y_test, prediccion)
indices = general_indices(MC,list(np.unique(Y)))
num_indices_list_dis_lin=[]
nom_indices_list_dis_lin=[]
for k in indices:
    print("\n%s:\n%s"%(k,str(indices[k])))
    num_indices_list_dis_lin.append(str(indices[k]))
    nom_indices_list_dis_lin.append(k)
    
print("Predictions in Testing using linear discriminant are:{}".format(lda.predict(X_test)))


LinearDiscriminantAnalysis(n_components=None, priors=None, shrinkage='auto',
              solver='lsqr', store_covariance=False, tol=0.0001)

Confusion Matriz:
[[90  0]
 [ 5 48]]

Global Precisión:
0.965034965034965

Global Error:
0.034965034965035

precision category:
     B        M
0  1.0  0.90566

Positive Precision:
90.56603773584906

Negative Precision:
100.0

Falses Positives:
0.0

Falsese Negatives:
0.09433962264150944

Positive Assertiveness:
1.0

Negative Assertiveness:
0.9473684210526315
Predictions in Testing using linear discriminant are:['M' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'B' 'M'
 'M' 'M' 'M' 'M' 'B' 'B' 'M' 'B' 'B' 'M' 'B' 'M' 'B' 'M' 'B' 'M' 'B' 'M'
 'B' 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'M' 'M' 'M' 'M' 'B'
 'B' 'B' 'B' 'B' 'B' 'M' 'M' 'M' 'B' 'B' 'M' 'B' 'M' 'M' 'M' 'B' 'B' 'M'
 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'B' 'M' 'M' 'M' 'B' 'M' 'B' 'B' 'B' 'M' 'M'
 'B' 'B' 'B' 'M' 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'B' 'M' 'B'
 'B'

D:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [9]:
#Default parameters
#square discriminant methods
qda = QuadraticDiscriminantAnalysis()
print(qda)
qda.fit(X_train, Y_train)
prediction = qda.predict(X_test)

MC = confusion_matrix(Y_test, prediction)
indices = general_indices(MC,list(np.unique(Y)))
num_indices_list_dis_cua=[]
nom_indices_list_dis_cua=[]
for k in indices:
    print("\n%s:\n%s"%(k,str(indices[k])))
    num_indices_list_dis_cua.append(str(indices[k]))
    nom_indices_list_dis_cua.append(k)
print("Predictions in Testing using quadratic discriminant are: {}".format(qda.predict(X_test)))

QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
               store_covariance=False, store_covariances=None, tol=0.0001)

Confusion Matriz:
[[86  4]
 [ 2 51]]

Global Precisión:
0.958041958041958

Global Error:
0.04195804195804198

precision category:
          B         M
0  0.955556  0.962264

Positive Precision:
96.22641509433963

Negative Precision:
95.55555555555556

Falses Positives:
0.044444444444444446

Falsese Negatives:
0.03773584905660377

Positive Assertiveness:
0.9272727272727272

Negative Assertiveness:
0.9772727272727273
Predictions in Testing using quadratic discriminant are: ['M' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'B' 'B' 'M' 'B' 'M' 'B' 'M'
 'M' 'M' 'M' 'M' 'B' 'B' 'M' 'B' 'B' 'M' 'B' 'M' 'B' 'M' 'B' 'M' 'B' 'M'
 'B' 'M' 'B' 'M' 'M' 'B' 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'M' 'M' 'M' 'B'
 'B' 'B' 'B' 'B' 'B' 'M' 'M' 'M' 'B' 'B' 'M' 'B' 'M' 'M' 'M' 'B' 'B' 'M'
 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'M' 'M' 'M' 'B' 'M' 'B' 'B' 'B' 'M' 'M'
 'B' 'M' 'B' 'M' 'B' 'B'

D:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Using the test table, calculate the confusion matrix, the precision, the positive precision, the negative precision, the false positives, the false negatives, the positive correctness and the negative correctness. Then build a comparison chart.

In [10]:
comparative_frame_df  = pd.DataFrame({'Metric Name':nom_indices_list_bayes, 'Bayes':num_indices_list_bayes,
                                       'Lineal discriminant':num_indices_list_dis_lin,  'Square discriminant':num_indices_list_dis_cua})
comparative_frame_df.reset_index(inplace = True)
comparative_frame_df.set_index('Metric Name', inplace = True)
del(comparative_frame_df['index'])
comparative_frame_df # Comparison chart

Bayes  \
Metric Name                                                          
Confusion Matriz                               [[86  4]\n [ 5 48]]   
Global Precisión                                0.9370629370629371   
Global Error                                   0.06293706293706292   
precision category                B        M\n0  0.955556  0.90566   
Positive Precision                               90.56603773584906   
Negative Precision                               95.55555555555556   
Falses Positives                              0.044444444444444446   
Falsese Negatives                              0.09433962264150944   
Positive Assertiveness                          0.9230769230769231   
Negative Assertiveness                           0.945054945054945   

                                     Lineal discriminant  \
Metric Name                                                
Confusion Matriz                     [[90  0]\n [ 5 48]]   
Global Precisión                       0.965034965034965   
Global Error                           0.034965034965035   
precision category           B        M\n0  1.0  0.90566   
Positive Precision                     90.56603773584906   
Negative Precision                                 100.0   
Falses Positives                                     0.0   
Falsese Negatives                    0.09433962264150944   
Positive Assertiveness                               1.0   
Negative Assertiveness                0.9473684210526315   

                                                 Square discriminant  
Metric Name                                                           
Confusion Matriz                                 [[86  4]\n [ 2 51]]  
Global Precisión                                   0.958041958041958  
Global Error                                     0.04195804195804198  
precision category                B         M\n0  0.955556  0.962264  
Positive Precision                                 96.22641509433963  
Negative Precision                                 95.55555555555556  
Falses Positives                                0.044444444444444446  
Falsese Negatives                                0.03773584905660377  
Positive Assertiveness                            0.9272727272727272  
Negative Assertiveness                            0.9772727272727273

Construya un cuadro comparativo con respecto a la tarea anterior. ¿Cual metodo es mejor?

R= los resultados aqui presentados cson mejores que la tarea anterior, ya que en general aqui se obtuvo mejor precision global y la precicion negativa fue superior en todos los casos que respecto a la tarea anterior que se tuvo una precision global 96% y negativa del 100% (en el caso del modelo con MLPClassifier solver=lbfgs y  que el modelo MLPClassifier solver=sgd no dio buenos resultados)

## Spam Data Prediction

In [11]:
SpamData = pd.read_csv("SpamData.csv",delimiter=';',decimal=".")
SpamData.head()

A.1   A.2   A.3  A.4   A.5   A.6   A.7   A.8   A.9  A.10  ...   A.49  \
0  0.00  0.64  0.64  0.0  0.32  0.00  0.00  0.00  0.00  0.00  ...   0.00   
1  0.21  0.28  0.50  0.0  0.14  0.28  0.21  0.07  0.00  0.94  ...   0.00   
2  0.06  0.00  0.71  0.0  1.23  0.19  0.19  0.12  0.64  0.25  ...   0.01   
3  0.00  0.00  0.00  0.0  0.63  0.00  0.31  0.63  0.31  0.63  ...   0.00   
4  0.00  0.00  0.00  0.0  0.63  0.00  0.31  0.63  0.31  0.63  ...   0.00   

    A.50  A.51   A.52   A.53   A.54   A.55  A.56  A.57  Tipo  
0  0.000   0.0  0.778  0.000  0.000  3.756    61   278  spam  
1  0.132   0.0  0.372  0.180  0.048  5.114   101  1028  spam  
2  0.143   0.0  0.276  0.184  0.010  9.821   485  2259  spam  
3  0.137   0.0  0.137  0.000  0.000  3.537    40   191  spam  
4  0.135   0.0  0.135  0.000  0.000  3.537    40   191  spam  

[5 rows x 58 columns]

Using Bayes, Linear Discriminant and Quadratic Discriminant, generate predictive models for the SpamData.csv table using 70% of the data for the learning table and 30% for the testing table.

In [12]:
X = SpamData.iloc[:,0:57] 
Y = SpamData.iloc[:,57:58] 
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size=0.70, random_state=0)

D:\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [13]:
#Bayes
# Default Parameters
bayes = GaussianNB()
print(bayes)
#Training the model
bayes.fit(X_train, Y_train)
prediction = bayes.predict(X_test)

MC = confusion_matrix(Y_test, prediction)
indices = general_indices(MC,list(np.unique(Y)))
num_indices_list_bayes=[]
nom_indices_list_bayes=[]
for k in indices:
    print("\n%s:\n%s"%(k,str(indices[k])))
    num_indices_list_bayes.append(str(indices[k]))
    nom_indices_list_bayes.append(k)

print("Predictions in Testing using naive bayes are: {}".format(bayes.predict(X_test)))


GaussianNB(priors=None, var_smoothing=1e-09)

Confusion Matriz:
[[597 225]
 [ 34 525]]

Global Precisión:
0.8124547429398986

Global Error:
0.1875452570601014

precision category:
      email      spam
0  0.726277  0.939177

Positive Precision:
93.91771019677996

Negative Precision:
72.62773722627736

Falses Positives:
0.2737226277372263

Falsese Negatives:
0.06082289803220036

Positive Assertiveness:
0.7

Negative Assertiveness:
0.9461172741679873
Predictions in Testing using naive bayes are: ['spam' 'spam' 'email' ... 'spam' 'spam' 'spam']


D:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [14]:
#linear discriminant methods
#Default Parameters
lda = LinearDiscriminantAnalysis(solver = 'lsqr', shrinkage = 'auto')
print(lda)
lda.fit(X_train, Y_train)
prediccion = lda.predict(X_test)

MC = confusion_matrix(Y_test, prediccion)
indices = general_indices(MC,list(np.unique(Y)))
num_indices_list_dis_lin=[]
nom_indices_list_dis_lin=[]
for k in indices:
    print("\n%s:\n%s"%(k,str(indices[k])))
    num_indices_list_dis_lin.append(str(indices[k]))
    nom_indices_list_dis_lin.append(k)
    
print("Predictions in Testing using linear discriminant are: {}".format(lda.predict(X_test)))


LinearDiscriminantAnalysis(n_components=None, priors=None, shrinkage='auto',
              solver='lsqr', store_covariance=False, tol=0.0001)

Confusion Matriz:
[[784  38]
 [136 423]]

Global Precisión:
0.8740043446777698

Global Error:
0.12599565532223023

precision category:
      email      spam
0  0.953771  0.756708

Positive Precision:
75.67084078711986

Negative Precision:
95.37712895377129

Falses Positives:
0.046228710462287104

Falsese Negatives:
0.24329159212880144

Positive Assertiveness:
0.9175704989154013

Negative Assertiveness:
0.8521739130434782
Predictions in Testing using linear discriminant are: ['spam' 'email' 'email' ... 'email' 'spam' 'email']


D:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [15]:
# We use the default parameters
#square discriminant methods
qda = QuadraticDiscriminantAnalysis()
print(qda)
qda.fit(X_train, Y_train)
prediccion = qda.predict(X_test)

MC = confusion_matrix(Y_test, prediccion)
indices = general_indices(MC,list(np.unique(Y)))
num_indices_list_dis_cua=[]
nom_indices_list_dis_cua=[]
for k in indices:
    print("\n%s:\n%s"%(k,str(indices[k])))
    num_indices_list_dis_cua.append(str(indices[k]))
    nom_indices_list_dis_cua.append(k)
print("Predictions in Testing using quadratic discriminant are: {}".format(qda.predict(X_test)))

D:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
               store_covariance=False, store_covariances=None, tol=0.0001)

Confusion Matriz:
[[586 236]
 [ 37 522]]

Global Precisión:
0.8023171614771905

Global Error:
0.19768283852280955

precision category:
      email     spam
0  0.712895  0.93381

Positive Precision:
93.38103756708408

Negative Precision:
71.28953771289538

Falses Positives:
0.2871046228710462

Falsese Negatives:
0.06618962432915922

Positive Assertiveness:
0.6886543535620053

Negative Assertiveness:
0.9406099518459069
Predictions in Testing using quadratic discriminant are: ['spam' 'spam' 'email' ... 'spam' 'spam' 'spam']


D:\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:692: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")


In [16]:
comparative_frame_df  = pd.DataFrame({'Metric Name':nom_indices_list_bayes, 'Bayes':num_indices_list_bayes,
                                       'Lineal discriminant':num_indices_list_dis_lin,  'Square discriminant':num_indices_list_dis_cua})
comparative_frame_df.reset_index(inplace = True)
comparative_frame_df.set_index('Metric Name', inplace = True)
del(comparative_frame_df['index'])
comparative_frame_df # Comparative chart

Bayes  \
Metric Name                                                            
Confusion Matriz                             [[597 225]\n [ 34 525]]   
Global Precisión                                  0.8124547429398986   
Global Error                                      0.1875452570601014   
precision category            email      spam\n0  0.726277  0.939177   
Positive Precision                                 93.91771019677996   
Negative Precision                                 72.62773722627736   
Falses Positives                                  0.2737226277372263   
Falsese Negatives                                0.06082289803220036   
Positive Assertiveness                                           0.7   
Negative Assertiveness                            0.9461172741679873   

                                                 Lineal discriminant  \
Metric Name                                                            
Confusion Matriz                             [[784  38]\n [136 423]]   
Global Precisión                                  0.8740043446777698   
Global Error                                     0.12599565532223023   
precision category            email      spam\n0  0.953771  0.756708   
Positive Precision                                 75.67084078711986   
Negative Precision                                 95.37712895377129   
Falses Positives                                0.046228710462287104   
Falsese Negatives                                0.24329159212880144   
Positive Assertiveness                            0.9175704989154013   
Negative Assertiveness                            0.8521739130434782   

                                               Square discriminant  
Metric Name                                                         
Confusion Matriz                           [[586 236]\n [ 37 522]]  
Global Precisión                                0.8023171614771905  
Global Error                                   0.19768283852280955  
precision category            email     spam\n0  0.712895  0.93381  
Positive Precision                               93.38103756708408  
Negative Precision                               71.28953771289538  
Falses Positives                                0.2871046228710462  
Falsese Negatives                              0.06618962432915922  
Positive Assertiveness                          0.6886543535620053  
Negative Assertiveness                          0.9406099518459069

## Zip Data Train Code Prediction

In [17]:
ZipDataTrainCod = pd.read_csv("ZipDataTrainCod.csv",delimiter=';',decimal=".")
ZipDataTrainCod.head()

Numero   V2   V3   V4     V5     V6     V7     V8     V9    V10  ...   \
0    seis -1.0 -1.0 -1.0 -1.000 -1.000 -1.000 -1.000 -0.631  0.862  ...    
1   cinco -1.0 -1.0 -1.0 -0.813 -0.671 -0.809 -0.887 -0.671 -0.853  ...    
2  cuatro -1.0 -1.0 -1.0 -1.000 -1.000 -1.000 -1.000 -1.000 -1.000  ...    
3   siete -1.0 -1.0 -1.0 -1.000 -1.000 -0.273  0.684  0.960  0.450  ...    
4    tres -1.0 -1.0 -1.0 -1.000 -1.000 -0.928 -0.204  0.751  0.466  ...    

    V248   V249   V250   V251   V252   V253   V254   V255   V256  V257  
0  0.304  0.823  1.000  0.482 -0.474 -0.991 -1.000 -1.000 -1.000  -1.0  
1 -0.671 -0.671 -0.033  0.761  0.762  0.126 -0.095 -0.671 -0.828  -1.0  
2 -1.000 -1.000 -1.000 -0.109  1.000 -0.179 -1.000 -1.000 -1.000  -1.0  
3 -0.318  1.000  0.536 -0.987 -1.000 -1.000 -1.000 -1.000 -1.000  -1.0  
4  0.466  0.639  1.000  1.000  0.791  0.439 -0.199 -0.883 -1.000  -1.0  

[5 rows x 257 columns]

In [18]:
ZipDataTestCod = pd.read_csv("ZipDataTestCod.csv",delimiter=';',decimal=".")
ZipDataTestCod.head()

Numero   V2   V3   V4     V5   V6     V7     V8     V9    V10  ...    V248  \
0  nueve -1.0 -1.0 -1.0 -1.000 -1.0 -0.948 -0.561  0.148  0.384  ...  -1.000   
1   seis -1.0 -1.0 -1.0 -1.000 -1.0 -1.000 -1.000 -1.000 -1.000  ...  -1.000   
2   tres -1.0 -1.0 -1.0 -0.593  0.7  1.000  1.000  1.000  1.000  ...   1.000   
3   seis -1.0 -1.0 -1.0 -1.000 -1.0 -1.000 -1.000 -1.000 -1.000  ...  -1.000   
4   seis -1.0 -1.0 -1.0 -1.000 -1.0 -1.000 -1.000 -0.858 -0.106  ...   0.901   

    V249   V250   V251   V252   V253  V254  V255  V256  V257  
0 -0.908  0.430  0.622 -0.973 -1.000  -1.0  -1.0  -1.0  -1.0  
1 -1.000 -1.000 -1.000 -1.000 -1.000  -1.0  -1.0  -1.0  -1.0  
2  0.717  0.333  0.162 -0.393 -1.000  -1.0  -1.0  -1.0  -1.0  
3 -1.000 -1.000 -1.000 -1.000 -1.000  -1.0  -1.0  -1.0  -1.0  
4  0.901  0.901  0.290 -0.369 -0.867  -1.0  -1.0  -1.0  -1.0  

[5 rows x 257 columns]

Using Bayes, Linear Discriminant, and Quadratic Discriminant generate predictive models for the learning table.

In [19]:
X1 = ZipDataTrainCod.iloc[:,1:257] 
Y1 = ZipDataTrainCod.iloc[:,0:1] 
X2 = ZipDataTestCod.iloc[:,1:257] 
Y2 = ZipDataTestCod.iloc[:,0:1] 
X_train = X1 
X_test = X2
Y_train = Y1
Y_test = Y2

In [20]:
#Bayes methods
bayes = GaussianNB()
print(bayes)
#Training the model
bayes.fit(X_train, Y_train)
prediccion = bayes.predict(X_test)

MC = confusion_matrix(Y_test, prediccion)

indices = general_indices(MC,list(np.unique(Y1)))

num_indices_list_bayes=[]
nom_indices_list_bayes=[]
for k in indices:
    print("\n%s:\n%s"%(k,str(indices[k])))
    num_indices_list_bayes.append(str(indices[k]))
    nom_indices_list_bayes.append(k)

print("Predictions in Testing using naive bayes are: {}".format(bayes.predict(X_test)))

GaussianNB(priors=None, var_smoothing=1e-09)

Confusion Matriz:
[[295   2   4  12   1  31  12   1   0   1]
 [ 10  74   2   2   7  23  36   2   3   1]
 [  0   1  56   4 117   5   8   5   0   4]
 [  2   4   3 141   1  31  12   1   3   0]
 [  0   0   2   0 153   3   0   9   0  10]
 [  1   5   2   5  39 110   2   0   1   1]
 [  3   2   0   5   0   3 151   0   0   6]
 [  0   0   3   1   9   1   0 132   0   1]
 [  6   4   1  10   9  48   4   6  78   0]
 [  0   0   1   1   3   1   4   0   0 254]]

Global Precisión:
0.7194818136522172

Global Error:
0.2805181863477828

precision category:
       cero   cinco  cuatro       dos     nueve      ocho      seis     siete  \
0  0.821727  0.4625    0.28  0.712121  0.864407  0.662651  0.888235  0.897959   

      tres       uno  
0  0.46988  0.962121  

Positive Precision:
88.09523809523809

Negative Precision:
99.32659932659934

Falses Positives:
0.006734006734006734

Falsese Negatives:
0.11904761904761904

Positive Assertiveness:
0.9736842105263158



D:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Predictions in Testing using naive bayes are: ['nueve' 'seis' 'tres' ... 'nueve' 'cero' 'uno']


In [21]:
#linear discriminant methods
# We use the default parameters
lda = LinearDiscriminantAnalysis(solver = 'lsqr', shrinkage = 'auto')
print(lda)
lda.fit(X_train, Y_train)
prediccion = lda.predict(X_test)

MC = confusion_matrix(Y_test, prediccion)
indices = general_indices(MC,list(np.unique(Y1)))
num_indices_list_dis_lin=[]
nom_indices_list_dis_lin=[]
for k in indices:
    print("\n%s:\n%s"%(k,str(indices[k])))
    num_indices_list_dis_lin.append(str(indices[k]))
    nom_indices_list_dis_lin.append(k)
    
print("Predictions in Testing using linear discriminant are: {}".format(lda.predict(X_test)))


LinearDiscriminantAnalysis(n_components=None, priors=None, shrinkage='auto',
              solver='lsqr', store_covariance=False, tol=0.0001)


D:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)



Confusion Matriz:
[[342   1   3   0   1   4   4   0   4   0]
 [  5 127   4   0   4   4   0   0  16   0]
 [  1   0 171   6  12   2   2   2   0   4]
 [  8   1  11 158   0  13   1   1   3   2]
 [  0   0   5   0 164   2   0   6   0   0]
 [  5   5   7   2   2 132   0   0  13   0]
 [  2   2   3   3   0   3 157   0   0   0]
 [  0   0   8   0   8   1   0 128   1   1]
 [  3   9   1   4   1   4   0   1 143   0]
 [  0   0   5   0   2   1   3   0   2 251]]

Global Precisión:
0.8834080717488789

Global Error:
0.11659192825112108

precision category:
       cero    cinco  cuatro      dos     nueve      ocho      seis     siete  \
0  0.952646  0.79375   0.855  0.79798  0.926554  0.795181  0.923529  0.870748   

       tres       uno  
0  0.861446  0.950758  

Positive Precision:
96.21212121212122

Negative Precision:
99.70845481049562

Falses Positives:
0.0029154518950437317

Falsese Negatives:
0.03787878787878788

Positive Assertiveness:
0.9921875

Negative Assertiveness:
0.9855907780979827
Predict

In [22]:
# We use the default parameters
#square discriminant methods
qda = QuadraticDiscriminantAnalysis()
print(qda)
qda.fit(X_train, Y_train)
prediction = qda.predict(X_test)

MC = confusion_matrix(Y_test, prediction)
indices = general_indices(MC,list(np.unique(Y1)))
num_indices_list_dis_cua=[]
nom_indices_list_dis_cua=[]
for k in indices:
    print("\n%s:\n%s"%(k,str(indices[k])))
    num_indices_list_dis_cua.append(str(indices[k]))
    nom_indices_list_dis_cua.append(k)
print("Predictions in Testing using quadratic discriminant are: {}".format(qda.predict(X_test)))

QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
               store_covariance=False, store_covariances=None, tol=0.0001)


D:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:692: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")



Confusion Matriz:
[[325   0   1  17   1  11   1   0   3   0]
 [  5 116   1   2   3  18  10   1   4   0]
 [  1   1 106   8  79   1   1   1   1   1]
 [  5   1   2 181   1   5   0   0   3   0]
 [  0   0   8   0 153   5   0   4   0   7]
 [  6   7   2  13  19 109   0   0   9   1]
 [  5   3   1   9   0   1 151   0   0   0]
 [  0   0   5   1   6   1   0 130   3   1]
 [  5   5   0   6   2  27   1   1 119   0]
 [  0   0   2   2   2   5   6   0   0 247]]

Global Precisión:
0.8156452416542103

Global Error:
0.18435475834578974

precision category:
       cero  cinco  cuatro       dos     nueve      ocho      seis     siete  \
0  0.905292  0.725    0.53  0.914141  0.864407  0.656627  0.888235  0.884354   

       tres       uno  
0  0.716867  0.935606  

Positive Precision:
95.86776859504133

Negative Precision:
100.0

Falses Positives:
0.0

Falsese Negatives:
0.04132231404958678

Positive Assertiveness:
1.0

Negative Assertiveness:
0.9848484848484849
Predictions in Testing using quadratic discri

In [23]:
comparative_frame_df  = pd.DataFrame({'Metric Name':nom_indices_list_bayes, 'Bayes':num_indices_list_bayes,
                                       'Lineal discriminant':num_indices_list_dis_lin,  'Square discriminant':num_indices_list_dis_cua})
comparative_frame_df.reset_index(inplace = True)
comparative_frame_df.set_index('Metric Name', inplace = True)
del(comparative_frame_df['index'])
comparative_frame_df # Comparative chart

Bayes  \
Metric Name                                                                 
Confusion Matriz        [[295   2   4  12   1  31  12   1   0   1]\n [...   
Global Precisión                                       0.7194818136522172   
Global Error                                           0.2805181863477828   
precision category             cero   cinco  cuatro       dos     nuev...   
Positive Precision                                      88.09523809523809   
Negative Precision                                      99.32659932659934   
Falses Positives                                     0.006734006734006734   
Falsese Negatives                                     0.11904761904761904   
Positive Assertiveness                                 0.9736842105263158   
Negative Assertiveness                                 0.9672131147540983   

                                                      Lineal discriminant  \
Metric Name                                                                 
Confusion Matriz        [[342   1   3   0   1   4   4   0   4   0]\n [...   
Global Precisión                                       0.8834080717488789   
Global Error                                          0.11659192825112108   
precision category             cero    cinco  cuatro      dos     nuev...   
Positive Precision                                      96.21212121212122   
Negative Precision                                      99.70845481049562   
Falses Positives                                    0.0029154518950437317   
Falsese Negatives                                     0.03787878787878788   
Positive Assertiveness                                          0.9921875   
Negative Assertiveness                                 0.9855907780979827   

                                                      Square discriminant  
Metric Name                                                                
Confusion Matriz        [[325   0   1  17   1  11   1   0   3   0]\n [...  
Global Precisión                                       0.8156452416542103  
Global Error                                          0.18435475834578974  
precision category             cero  cinco  cuatro       dos     nueve...  
Positive Precision                                      95.86776859504133  
Negative Precision                                                  100.0  
Falses Positives                                                      0.0  
Falsese Negatives                                     0.04132231404958678  
Positive Assertiveness                                                1.0  
Negative Assertiveness                                 0.9848484848484849